import os
import pandas as pd

data=pd.read_csv("F:\Testwel_new.csv",index_col=0,na_values=["???","###"])
data1=pd.read_excel("F:\Book1.xlsx",sheet_name="Hello",index_col=0,na_values=["###","$$$"])
print(data)
print(data1)
print("#############################################################################")
data2=pd.read_table(r"F:\Python_read.txt",sep="\t")
print(data2)
print("Text in csv file")
data3=pd.read_csv(r"F:\Python_read.txt",sep="\t")
print(data3)
print(data.index)
print(data.columns)
print(data.size)
print(data.shape)
print(data.memory_usage(index=True,deep=True))
print(data.ndim)
print(data.head(6))
print(data.at[4,'Country'])
print(data.iat[5,1])
print(data.loc[:,['Country','Product']])
print(data.dtypes)
print(data.select_dtypes(exclude=[object])
print(data.info())
